import React from 'react';

const SectionPrintTemplate = React.forwardRef(({ section, record, business }, ref) => {
  if (!section || !record) return <div ref={ref} />;

  return (
    <div ref={ref} style={{ padding: '40px', fontFamily: 'Arial, sans-serif', maxWidth: '210mm', color: '#111' }}>
      {/* Business Header */}
      <div style={{ textAlign: 'center', marginBottom: '24px', paddingBottom: '16px', borderBottom: `3px solid ${section.color || '#1976d2'}` }}>
        {business?.logo && (
          <img src={business.logo} alt="Logo" style={{ height: '56px', marginBottom: '8px', objectFit: 'contain' }} />
        )}
        <h2 style={{ margin: '0 0 4px', fontSize: '20px', fontWeight: 700 }}>{business?.name || ''}</h2>
        {business?.address && <p style={{ margin: '2px 0', fontSize: '12px', color: '#555' }}>{business.address}</p>}
        {business?.phone && <p style={{ margin: '2px 0', fontSize: '12px', color: '#555' }}>Phone: {business.phone}</p>}
        {business?.gstNumber && <p style={{ margin: '2px 0', fontSize: '12px', color: '#555' }}>GST: {business.gstNumber}</p>}
      </div>

      {/* Section Title */}
      <div style={{ marginBottom: '20px' }}>
        <h3 style={{ margin: '0 0 12px', fontSize: '17px', fontWeight: 700, color: section.color || '#1976d2', textTransform: 'uppercase', letterSpacing: '1px' }}>
          {section.name}
        </h3>
        <div style={{ display: 'flex', gap: '32px', fontSize: '13px', padding: '8px 12px', backgroundColor: '#f5f5f5', borderRadius: '4px' }}>
          {record.partyName && (
            <span><strong>Customer:</strong> {record.partyName}</span>
          )}
          <span><strong>Date:</strong> {record.date}</span>
        </div>
      </div>

      {/* Fields Table — grouped by tab if multiple tabs exist */}
      {(() => {
        const tabs = section.tabs?.length > 0 ? section.tabs : null;
        const fieldList = tabs ? null : (section.fields || []);
        const multiTab = tabs && tabs.length > 1;

        const renderRows = (fields, rowOffset = 0) =>
          fields.map((field, idx) => {
            const val = record.fields?.[field.id];
            if (val === undefined || val === '') return null;
            return (
              <tr key={field.id} style={{ backgroundColor: (idx + rowOffset) % 2 === 0 ? '#fafafa' : '#fff' }}>
                <td style={{ padding: '9px 14px', fontWeight: 600, width: '38%', borderBottom: '1px solid #e8e8e8', color: '#444' }}>
                  {field.name}
                </td>
                <td style={{ padding: '9px 14px', borderBottom: '1px solid #e8e8e8', color: '#111' }}>
                  {val}{field.unit && val ? ` ${field.unit}` : ''}
                </td>
              </tr>
            );
          });

        if (tabs) {
          return tabs.map(tab => (
            <div key={tab.id} style={{ marginBottom: '16px' }}>
              {multiTab && (
                <div style={{
                  padding: '6px 14px', marginBottom: '4px',
                  backgroundColor: section.color || '#1976d2',
                  color: '#fff', fontWeight: 700, fontSize: '12px',
                  borderRadius: '4px', letterSpacing: '0.5px'
                }}>
                  {tab.name}
                </div>
              )}
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                <tbody>{renderRows(tab.fields || [])}</tbody>
              </table>
            </div>
          ));
        }

        return (
          <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '20px', fontSize: '13px' }}>
            <tbody>{renderRows(fieldList)}</tbody>
          </table>
        );
      })()}

      {/* Notes */}
      {record.notes && (
        <div style={{ padding: '12px 16px', backgroundColor: '#f9f9f9', borderLeft: `4px solid ${section.color || '#1976d2'}`, borderRadius: '0 4px 4px 0', marginTop: '16px' }}>
          <strong style={{ fontSize: '13px', display: 'block', marginBottom: '4px' }}>Notes</strong>
          <p style={{ margin: 0, fontSize: '13px', color: '#444', whiteSpace: 'pre-wrap' }}>{record.notes}</p>
        </div>
      )}

      {/* Footer */}
      <div style={{ marginTop: '40px', paddingTop: '12px', borderTop: '1px solid #ddd', textAlign: 'center', fontSize: '11px', color: '#aaa' }}>
        Generated by Solo Books
      </div>
    </div>
  );
});

SectionPrintTemplate.displayName = 'SectionPrintTemplate';
export default SectionPrintTemplate;
